# Java Exception

## Exception

- Exception adalah sebuah event yang terjadi selama eksekusi program dan mengganggu alur normal dari program tersebut.
- Exception adalah sebuah object yang terjadi pada saat runtime, dan mengganggu alur normal dari program tersebut.
- Exception adalah sebuah event yang terjadi selama eksekusi program dan mengganggu alur normal dari program tersebut.

## Membuat Exception

- Untuk membuat exception kita bisa membuat class yang extends ke class Exception / Throwable atau turunan-turunannya.

```java
public class ValidationException extends Throwable{
    public ValidationException(String message) {
        super(message);
    }
}
```

## Throw Exception

- Untuk melempar exception kita bisa menggunakan keyword throw.
- Throw keyword digunakan untuk melempar exception yang sudah dibuat.
- Biasanya kita membuat exception untuk menangani error yang spesifik di dalam sebuah method.

```java
public class ValidationUtil {
    public static void validate(LoginRequest LoginRequest) throws ValidationException {
        if (LoginRequest.username() == null) {
            throw new ValidationException("Username is null");
        } else if (LoginRequest.username().isBlank()) {
            throw new ValidationException("Username is blank");
        } else if (LoginRequest.password() == null) {
            throw new ValidationException("Password is null");
        } else if (LoginRequest.password().isBlank()) {
            throw new ValidationException("Password is blank");
        }
    }
}
```

## Try Catch

Saat kita melempar/throw exception, kita harus menangkapnya dengan menggunakan try catch.

```java
public class ValidationApp {
    public static void main(String[] args) {
        LoginRequest loginRequest = new LoginRequest(null, null);
        try {
            ValidationUtil.validate(loginRequest);
            System.out.println("Data valid");
        } catch (ValidationException exception) {
            System.out.println("Data tidak valid : " + exception.getMessage());
        } finally {
            System.out.println("Selalu di eksekusi");
        }
    }
}
```

## Runtime Exception

Secara garis besar ada 3 jenis exception di Java:

- Checked Exception / Compile Time Exception -> Exception yang wajib di try catch
- Unchecked Exception / Runtime Exception -> Exception yang tidak wajib di try catch
- Error

## Runtime Exception

- RuntimeException adalah exception yang tidak wajib di try catch.

```java
public class BlankException extends RuntimeException{
    public BlankException(String message) {
        super(message);
    }
}
```

```java
public class ValidateRuntime {
    public static void validate(LoginRequest LoginRequest) {
        if (LoginRequest.username() == null) {
            throw new NullPointerException("Username is null");
        } else if (LoginRequest.username().isBlank()) {
            throw new BlankException("Username is blank");
        } else if (LoginRequest.password() == null) {
            throw new NullPointerException("Password is null");
        } else if (LoginRequest.password().isBlank()) {
            throw new BlankException("Password is blank");
        }
    }
}

// tidak wajib menambahkan throws
```

```java
public class RuntimeApp {
    public static void main(String[] args) {
        LoginRequest loginRequest = new LoginRequest(null, null);
        try {
            ValidateRuntime.validate(loginRequest);
            System.out.println("Data valid");
        } catch (RuntimeException exception) {
            System.out.println("Data tidak valid : " + exception.getMessage());
        } finally {
            System.out.println("Selalu di eksekusi");
        }
    }
}
```

## Error

- Error adalah exception yang terjadi di luar kendali programmer.
- Biasanya error terjadi karena masalah resource yang tidak cukup.
- Error tidak perlu di try catch.

```java
public class DatabaseError extends Error{
    public DatabaseError(String message) {
        super(message);
    }
}
```

```java
public class DatabaseApp {
    public static void main(String[] args) {
        connectDatabase("fitron", "Rahasia");
        System.out.println("Sukses connect database");
    }

    public static void connectDatabase(String username, String password) {
        if (username == null || password == null) {
            throw new DatabaseError("Tidak bisa connect ke database");
        }
    }
}
```

## StackTraceElement Class

- Throwable memiliki method getStackTrace() yang mengembalikan array dari StackTraceElement object.
- StackTraceElement memiliki method getClassName(), getMethodName(), getLineNumber() dan lain-lain.
- Method getStackTrace() biasanya digunakan untuk mencari tahu dimana letak error terjadi.

```java
public class StackTraceApp {
    public static void main(String[] args) {
        try {
            SampleError();
        } catch (RuntimeException exception) {
            exception.printStackTrace();
        }
    }

    public static void SampleError() {
        try {
            String[] names = {
                    "Fitron", "Kia", "Nara"
            };

            System.out.println(names[100]);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }
}
```

## Try With Resources

- Try with resources adalah sebuah fitur baru di Java dimana kita bisa membuat sebuah blok try dengan sebuah resource.
- Resource adalah object yang harus di close setelah blok try selesai di eksekusi.


```java
public class ReadApp {
    public static void main(String[] args) {
        try (BufferedReader reader = new BufferedReader(new FileReader("README.md"))) {
            while (true) {
                String line = reader.readLine();
                if (line == null) {
                    break;
                }
                System.out.println(line);
            }
        } catch (Throwable throwable) {
            System.out.println("Error membaca file " + throwable.getMessage());
        }
    }
}
``` 